server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端实例名称
  client:
    fetch-registry: false #表示自己就是注册中心，不需要进行检索服务
    register-with-eureka: false # 不向注册中心注册自己
    service-url:
      # 设置与EurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eureka7002.com:7002/eureka/